server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000Mb # Max file size 默认1M
      max-request-size: 2500Mb # max request size  默认10M
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
