eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
server:
  port: 9102
spring:
  application:
    name: trace-two
  zipkin:
    base-url: http://localhost:9411
